"""empty message

Revision ID: 6672bd9f5c3d
Revises:
Create Date: 2017-03-19 12:56:07.489084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6672bd9f5c3d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():

    op.create_table(
        'results',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('url', sa.String(255), nullable=False),
        sa.Column('agency', sa.String(255), nullable=True),
        sa.Column('fsg', sa.String(255), nullable=True),
        sa.Column('source', sa.String(255), nullable=True),
        sa.Column('title', sa.String(255), nullable=True),
        sa.Column('keywords', sa.String(255), nullable=True),
        sa.Column('url_2', sa.String(255), nullable=True),
        sa.Column('naics_code', sa.String(255), nullable=True),
        sa.Column('psc_code', sa.String(255), nullable=True),
        sa.Column('contact_info', sa.String(255), nullable=True),
        sa.Column('place_of_performance', sa.String(255), nullable=True),
        sa.Column('link_to_solicitation', sa.String(255), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),

        sa.Column('date', sa.DateTime(), nullable=True),


        sa.PrimaryKeyConstraint('id')
    )


def downgrade():
    # commands auto generated by Alembic - please adjust! ###
    op.drop_table('results')
